// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saffron.API.Data;

namespace Saffron.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Saffron.API.Data.Models.CookbookDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Cookbook");

                    b.HasData(
                        new { Id = new Guid("8e3366ff-50f9-4606-8691-2f7406e47ab8"), Title = "Indian" }
                    );
                });

            modelBuilder.Entity("Saffron.API.Data.Models.CookBookRecipesDAO", b =>
                {
                    b.Property<Guid>("CookbookId");

                    b.Property<Guid>("RecipeId");

                    b.HasKey("CookbookId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("CookBookRecipeBind");
                });

            modelBuilder.Entity("Saffron.API.Data.Models.CookingTimeDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Hours");

                    b.Property<int>("Minutes");

                    b.Property<Guid>("RecipeId");

                    b.Property<string>("TimeTitle");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("CookingTime");
                });

            modelBuilder.Entity("Saffron.API.Data.Models.IngradientDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Keywords");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<double>("Quantity");

                    b.Property<Guid>("RecipeId");

                    b.Property<string>("Units");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingradient");
                });

            modelBuilder.Entity("Saffron.API.Data.Models.RecipeDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("PhotoUrl");

                    b.Property<string>("Source");

                    b.Property<string>("SourceUrl");

                    b.Property<string>("Steps");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<string>("Yield");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new { Id = new Guid("37f5087c-d956-4269-817c-21f6ef35e093"), Title = "Chicken Tikka Masala" }
                    );
                });

            modelBuilder.Entity("Saffron.API.Data.Models.SectionDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CookbookId");

                    b.Property<int>("Order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.HasIndex("CookbookId");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("Saffron.API.Data.Models.CookBookRecipesDAO", b =>
                {
                    b.HasOne("Saffron.API.Data.Models.CookbookDAO", "Cookbook")
                        .WithMany()
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Saffron.API.Data.Models.RecipeDAO", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Saffron.API.Data.Models.CookingTimeDAO", b =>
                {
                    b.HasOne("Saffron.API.Data.Models.RecipeDAO", "Recipe")
                        .WithMany("CookingTime")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Saffron.API.Data.Models.IngradientDAO", b =>
                {
                    b.HasOne("Saffron.API.Data.Models.RecipeDAO", "Recipe")
                        .WithMany("Ingradients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Saffron.API.Data.Models.SectionDAO", b =>
                {
                    b.HasOne("Saffron.API.Data.Models.CookbookDAO", "Cookbook")
                        .WithMany("Sections")
                        .HasForeignKey("CookbookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
